export const LightTheme = {
    dark: false,
    colors: {
        primaryBaseColor: '#6E8BB8',
        secondaryBaseColor: '#F1F1F1',
        tertiaryBaseColor: '#D4DBE6',
        dangerBaseColor: '#F06868',
        primaryBorderColor: '#DCDCDC',
        secondaryBorderColor: '#D4DBE6',
        tertiaryBorderColor: '#6E8BB8',
        primaryTextColor: '#4b688c',
        secondaryTextColor: '#808080',//'#A4BCE3',
        tertiaryTextColor: '#F1F1F1',
        quaternaryTextColor: '#6E8BB8',
        quintenaryTextColor: '#99ABC9',
        dangerTextColor: '#F06868',
        primaryMonetaryColor: '#3C66F0',
        secondaryMonetaryColor: '#F06868',
        tertiaryMonetaryColor: '#4CA346',
        primaryIcon: '#F1F1F1',
        secondaryIcon: '#A4BCE3',
        tertiaryIcon: '#00A519',
        quaternaryIcon: '#6E8BB8',
        quintenaryIcon: '#4b688c',
        primaryAreaDashboard: '#D4DBE6',
        tertiaryAreaDashboard: '#F1F1F1',
        primaryBorderDashboard: '#6E8BB8',
        primaryTextDashboard: '#6E8BB8',
        secondaryTextDashboard: '#F1F1F1',
        primaryIconDashboard: '#6E8BB8',
        secondaryIconDashboard: '#A4BCE3'
    },
};

export const DarkTheme = {
    dark: true,
    colors: {
        primaryBaseColor: '#212121',
        secondaryBaseColor: '#414141',
        tertiaryBaseColor: '#303030',
        dangerBaseColor: '#F06868',
        primaryBorderColor: '#ffffff26',
        secondaryBorderColor: '#ffffff0d',
        tertiaryBorderColor: '#f3f3f3',
        primaryTextColor: '#fff',
        secondaryTextColor: '#afafaf',//'#A4BCE3',
        tertiaryTextColor: '#f3f3f3',
        quaternaryTextColor: '#212121',
        quintenaryTextColor: '#99ABC9',
        dangerTextColor: '#F06868',
        primaryMonetaryColor: '#66b5ff',
        secondaryMonetaryColor: '#ff8583',
        tertiaryMonetaryColor: '#93c790',
        primaryIcon: '#f3f3f3',
        secondaryIcon: '#afafaf',
        tertiaryIcon: '#00A519',
        quaternaryIcon: '#212121',
        quintenaryIcon: '#f3f3f3',
        primaryAreaDashboard: '#303030',
        tertiaryAreaDashboard: '#414141',
        primaryBorderDashboard: '#212121',
        primaryTextDashboard: '#f3f3f3',
        secondaryTextDashboard: '#f3f3f3',
        primaryIconDashboard: '#f3f3f3',
        secondaryIconDashboard: '#f3f3f3',
    },
};