# Generated by Django 3.2.5 on 2021-07-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='last_updated',
            new_name='dt_alteracao',
        ),
        migrations.RenameField(
            model_name='codes',
            old_name='created',
            new_name='dt_criacao',
        ),
    ]
