# Generated by Django 3.2.5 on 2021-07-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210726_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentos',
            options={'ordering': ['-dt_criacao', 'ope_id']},
        ),
        migrations.AddField(
            model_name='saldos',
            name='dt_saldo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
