# Generated by Django 3.2.5 on 2021-08-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210730_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='contas',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='movimentos',
            options={'ordering': ['ope_id__tipo', 'dt_criacao']},
        ),
        migrations.AlterModelOptions(
            name='operacoes',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='movimentos',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
