# Generated by Django 3.2.5 on 2021-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_saldosimulado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimentos',
            index=models.Index(fields=['ope_id'], name='website_mov_ope_id__057155_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentos',
            index=models.Index(fields=['cta_id'], name='website_mov_cta_id__63c6a3_idx'),
        ),
    ]
