# Generated by Django 3.2.5 on 2021-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210802_1724'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimentos',
            name='website_mov_ope_id__057155_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentos',
            name='website_mov_cta_id__63c6a3_idx',
        ),
        migrations.AddIndex(
            model_name='movimentos',
            index=models.Index(fields=['dt_criacao'], name='website_mov_dt_cria_69d51c_idx'),
        ),
    ]
