# Generated by Django 3.2.5 on 2021-08-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210802_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='recorrente',
            field=models.IntegerField(default=0),
        ),
    ]
