# Generated by Django 3.2.5 on 2021-08-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_operacoes_recorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucoes',
            name='dt_exec_rec',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucoes',
            name='executa_recorrencia',
            field=models.IntegerField(default=0),
        ),
    ]
