# Generated by Django 3.2.5 on 2021-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210802_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldos',
            name='vlr_dividendo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saldos',
            name='vlr_rendimento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saldos',
            name='vlr_valorizacao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
