# Generated by Django 3.2.5 on 2021-08-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210803_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.contas', verbose_name='contas'),
        ),
    ]
