# Generated by Django 3.2.5 on 2022-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contas_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucoes',
            name='dt_exec_saldo_sim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucoes',
            name='executa_saldo_sim',
            field=models.IntegerField(default=0),
        ),
    ]
