# Generated by Django 3.2.5 on 2022-05-07 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20220507_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasOperacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.contas', verbose_name='contas')),
                ('operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.operacoes', verbose_name='operacoes')),
            ],
        ),
    ]
