# Generated by Django 3.2.5 on 2022-05-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contasoperacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasoperacoes',
            name='dt_base',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
