# Generated by Django 3.2.5 on 2022-05-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_saldosimulado_executa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldosimulado',
            old_name='executa',
            new_name='ajusta',
        ),
    ]
