# Generated by Django 3.2.5 on 2022-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_rename_executa_saldosimulado_ajusta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='dt_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
