# Generated by Django 3.2.5 on 2022-05-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
