# Generated by Django 3.2.5 on 2022-05-30 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('vlr_compra', models.FloatField(blank=True, null=True)),
                ('vlr_venda', models.FloatField(blank=True, null=True)),
                ('perc_irpf', models.FloatField(blank=True, null=True)),
                ('vlr_irpf', models.FloatField(blank=True, null=True)),
                ('vlr_despesas', models.FloatField(blank=True, null=True)),
                ('vlr_retorno_bruto', models.FloatField(blank=True, null=True)),
                ('vlr_retorno_liq', models.FloatField(blank=True, null=True)),
                ('periodo_meses', models.IntegerField(blank=True, null=True)),
                ('dt_vencimento', models.DateTimeField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.saldos',),
        ),
    ]
