# Generated by Django 3.2.5 on 2022-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20220530_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='perc_retorno_liq',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
