# Generated by Django 3.2.5 on 2022-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_ativos_perc_retorno_liq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='perc_retorno_liq',
            field=models.FloatField(default=0.0),
        ),
    ]
