# Generated by Django 3.2.5 on 2022-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_ativos_perc_retorno_liq'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='salario',
            field=models.IntegerField(default=0),
        ),
    ]
