# Generated by Django 3.2.5 on 2022-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_operacoes_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldos',
            name='credito_salario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saldos',
            name='debito_salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
