# Generated by Django 3.2.5 on 2022-09-13 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20220805_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposAtivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ativos',
            name='situacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ativos',
            name='tipo_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.tiposativos', verbose_name='tipos_ativos'),
        ),
    ]
