# Generated by Django 3.2.5 on 2022-09-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20220913_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposativos',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposativos',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
