# Generated by Django 3.2.5 on 2022-09-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20220913_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposativos',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.contas', verbose_name='contas'),
        ),
    ]
