# Generated by Django 3.2.5 on 2023-03-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_tiposativos_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentos',
            name='consolidado',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_destino', to='website.contas', verbose_name='contas'),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='movimento_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.movimentos', verbose_name='movimentos'),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='total_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
