# Generated by Django 3.2.5 on 2023-03-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_operacoes_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_destino', to='website.contas', verbose_name='Conta Destino'),
        ),
        migrations.AlterField(
            model_name='movimentos',
            name='cta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.contas', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='movimentos',
            name='movimento_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.movimentos', verbose_name='Movimento'),
        ),
        migrations.AlterField(
            model_name='movimentos',
            name='ope_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.operacoes', verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='recorrente',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='salario',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='status',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=1),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Crédito'), (2, 'Débito'), (3, 'Transferência')]),
        ),
    ]
