import {StyleSheet} from 'react-native';

export const getPortfolioViewStyle = (theme: any) => StyleSheet.create({
    container: {
        paddingHorizontal: 10,   
        paddingVertical: 10,
    },
    headerCard: {
        flexDirection: 'row',
        alignItems: 'center',   
        backgroundColor: theme.colors.secondaryBaseColor,
        borderRadius: 12,
        padding: 15,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: theme.colors.primaryBorderColor,
    },
    headerIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: theme.colors.tertiaryBaseColor,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    headerContent: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
    },
    headerSubtitle: {
        fontSize: 14,
        color: theme.colors.secondaryTextColor,
        fontFamily: 'Open Sans',
        marginTop: 2,
    },
    textLink: {
        color: theme.colors.primaryTextColor,
        fontSize: 16,
        fontFamily: "Open Sans",
        textDecorationLine: "underline"
    },
    statusTag: {
        marginTop: 5,
        alignSelf: 'flex-start',
    },
    valueSection: {
        marginBottom: 20,
    },
    sectionLabel: {
        fontSize: 12,
        color: theme.colors.quaternaryTextColor,
        fontFamily: 'Open Sans',
        marginBottom: 5,
    },
    mainValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
    },
    updateDate: {
        fontSize: 12,
        color: theme.colors.secondaryTextColor,
        fontFamily: 'Open Sans',
        marginTop: 5,
    },
    box: {
        marginVertical: 10,
        borderWidth: 1,
        borderColor: theme.colors.primaryBorderColor + "46",
        borderRadius: 20,
        padding: 10
    },
    growthValue: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.sextenaryTextColor,
        fontFamily: 'Open Sans',
    },
    growthLabel: {
        fontSize: 12,
        color: theme.colors.quaternaryTextColor,
        fontFamily: 'Open Sans',
    },
    twoColumnRow: {
        flexDirection: 'row',
        gap: 15,
        marginBottom: 20,
    },
    columnItem: {
        flex: 1,
    },
    columnValue: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
        marginTop: 8,
    },
    actionItemContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: theme.colors.secondaryBaseColor,
        borderRadius: 10,
        padding: 15,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: theme.colors.primaryBorderColor,
    },
    actionItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    actionItemIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: theme.colors.tertiaryBaseColor,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    actionItemText: {
        flex: 1,
    },
    actionItemTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
    },
    actionItemSubtitle: {
        fontSize: 12,
        color: theme.colors.secondaryTextColor,
        fontFamily: 'Open Sans',
        marginTop: 2,
    },
    sectionHeader: {
        fontSize: 16,
        fontWeight: '900',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
        marginBottom: 12,
        marginTop: 15,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.primaryBorderColor,
    },
    infoLabel: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        gap: 10,
    },
    infoLabelText: {
        fontSize: 14,
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
        textAlign: 'right',
        flex: 1,
    },
    transactionHistoryItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.primaryBorderColor,
    },
    transactionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    transactionDate: {
        alignItems: 'center',
    },
    transactionDay: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
    },
    transactionMonth: {
        fontSize: 11,
        color: theme.colors.secondaryTextColor,
        fontFamily: 'Open Sans',
        marginTop: 2,
    },
    transactionYear: {
        fontSize: 11,
        color: theme.colors.secondaryTextColor,
        fontFamily: 'Open Sans',
    },
    transactionDetails: {
        flex: 1,
    },
    transactionTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
    },
    transactionType: {
        fontSize: 12,
        color: theme.colors.sextenaryTextColor,
        fontFamily: 'Open Sans',
        marginTop: 2,
    },
    transactionValue: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.primaryTextColor,
        fontFamily: 'Open Sans',
    },
    viewAllButton: {
        alignItems: 'center',
        paddingVertical: 15,
        marginTop: 10,
    },
    viewAllText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.quaternaryBaseColor,
        fontFamily: 'Open Sans',
    },
});
